### ISSUE TITLE
Question: Support for LCD

### ISSUE THREAD

**Issue by abhatikar** [ZinggJM/GxTFT#10]
Hi,

i am looking for using this display with raspberry pi 3 or Arduino compatible boards like esp...
Any idea ?

https://www.aliexpress.com/item/EYEWINK-New-4-inch-TFT-LCD-screen-touch-screen-module-IPS-full-view-Ultra-HD-800X480/32807629460.html

thanks

**Comment by ZinggJM** [comment]
I have the same display from the same shop. It didn't work and still doesn't. But the same display from a different shop does, it works with a STM32F407ZG board. See myTFTs/my_3.97_800x480_OTM8009A_STM32F407ZGM4_FSMC.h. and the files referenced there.
The display needs 5V on the VCC pin.
I don't think it would work with ESP32, needs more pins.
See also [https://forum.arduino.cc/index.php?topic=495044.0](url)

**Comment by abhatikar** [comment]
Thanks for the reply, any idea only to get the display working on Raspberry Pi ? Any inputs would be appreciated.
