### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by gigajoules** [ZinggJM/GxTFT#12]
Hi, 

I am currently trying to get a PV0430H2Z0  from kingtech running, but I am totally bamboozled by this library. 
Can you advise me on how I could get the screen running. 

Also is there a list of drawing functions somewhere?

**Comment by ZinggJM** [comment]
No help is available for this library, sorry. The "list of drawing functions" is the list of class methods in the header files. There are 2 (selectable) display classes, GxTFT and GxTFT_GFX. GxTFT_GFX inherits from Adafruit_GFX, see the documentation there, GxTFT does not inherit from Adafruit_GFX, but has same or similar methods.

I can't help you with your display, I would need to have one myself to learn about it.
