### ISSUE TITLE
Teensy 3.5 compatibility

### ISSUE THREAD

**Issue by gigajoules** [ZinggJM/GxTFT#13]
Is it possible to use this library with a teensy 3.5? 
If not, is there any chance you could add compatibility?

**Comment by ZinggJM** [comment]
I think this is possible, as there exists an Arduino package for Teensy 3.5 afaik.
For any display to use on any Arduino compatible processor, a GxIO class would need to be created, in addition to the controller class, to use with GxTFT.
I assume the Teensy has not enough IO pins for your parallel 16bit data display.
I can only add support for processor boards and displays that I have, and can get hands on documentation and demo example code.

**Comment by gigajoules** [comment]
Oh the teensy has a LOT of pins and I beleive it's more powerful than the mega?
