### ISSUE TITLE
Support ssd1289

### ISSUE THREAD

**Issue by vadimkkkk** [ZinggJM/GxTFT#15]
Hello ! Is it possible to support ssd1289 ??

**Comment by ZinggJM** [comment]
@vadimkkkk 

It would be possible, by adding a GxCTRL_SSD1289 class to the library, but I have no TFT with this controller.
I think SSD1289 is supported by MCUFRIEND_KBV; usually I use this library when I try out a new TFT.
And I usually extract code from there when I add a new TFT to my library.
GxTFT only supports TFTs I have. Different TFTs with the same controller may not be supported.
